version: '3.8'

services:
  reservations:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run start:dev
  mongo:
    image: mongo